export const ErrorCodes = {
  INVALID_REQUEST: 'INVALID_REQUEST',
  INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
  DUPLICATE_REFERENCE: 'DUPLICATE_REFERENCE',
  TRANSACTION_PENDING: 'TRANSACTION_PENDING',
  FINERACT_UNAVAILABLE: 'FINERACT_UNAVAILABLE',
  FINERACT_ERROR: 'FINERACT_ERROR',
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_ALREADY_EXISTS: 'WALLET_ALREADY_EXISTS',
  MERCHANT_NOT_FOUND: 'MERCHANT_NOT_FOUND',
  MERCHANT_INACTIVE: 'MERCHANT_INACTIVE',
  KYC_INCOMPLETE: 'KYC_INCOMPLETE',
  KYC_FAILED: 'KYC_FAILED',
  KYC_NOT_CONFIGURED: 'KYC_NOT_CONFIGURED',
  DAILY_LIMIT_EXCEEDED: 'DAILY_LIMIT_EXCEEDED',
  INVALID_BENEFICIARY: 'INVALID_BENEFICIARY',
  BANK_UNAVAILABLE: 'BANK_UNAVAILABLE',
  BANK_REJECTED: 'BANK_REJECTED',
  BANK_NOT_CONFIGURED: 'BANK_NOT_CONFIGURED',
  PAYOUT_NOT_FOUND: 'PAYOUT_NOT_FOUND',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  ORGANIZATION_NOT_FOUND: 'ORGANIZATION_NOT_FOUND',
  INVALID_HIERARCHY: 'INVALID_HIERARCHY',
  BANK_DISABLED: 'BANK_DISABLED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  BENEFICIARY_NOT_FOUND: 'BENEFICIARY_NOT_FOUND',
  WEBHOOK_NOT_FOUND: 'WEBHOOK_NOT_FOUND',
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  PER_TX_LIMIT_EXCEEDED: 'PER_TX_LIMIT_EXCEEDED',
  FUNDING_CHANNEL_UNAVAILABLE: 'FUNDING_CHANNEL_UNAVAILABLE',
  MPIN_INVALID: 'MPIN_INVALID',
  MPIN_NOT_SET: 'MPIN_NOT_SET',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export class NexaraError extends Error {
  constructor(
    public readonly code: ErrorCode,
    message: string,
    public readonly status = 400,
  ) {
    super(message);
    this.name = 'NexaraError';
  }
}
